[package]
name = "shellcode_encrypter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libaes = "0.6.4"
clap = { version = "4.1.11", features = ["derive"]}